name: Deployment
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  CI: false
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies
      run: |
        npm install
        npm install --save-dev karma-junit-reporter karma-coverage karma-sonarqube-unit-reporter
    - name: Run Tests
      run: npm run test:ci
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ github.run_id }}
        path: |
          reports/junit/test-results.xml
          coverage/lcov/lcov.info
          coverage/cobertura.xml
        overwrite: true

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: dist/vf-angular-boilerplate

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v4
    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-output
        path: dist/vf-angular-boilerplate
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: dist/vf-angular-boilerplate
