name: Deployment
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  CI: false
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm install
        npm install --save-dev karma-junit-reporter karma-coverage karma-sonarqube-unit-reporter
    - name: Run Tests
      run: npm run test:ci
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: |
          reports/junit/test-results.xml
          coverage/lcov/lcov.info
          coverage/cobertura.xml

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Download Build Artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-output
        path: ./build
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./build
